title: Eshan Inamdar # your name (or website title) here
logo: "/images/linkedin.jpg?raw=true" # your photo (or logo) here
email: ehinamdar@gmail.com
linkedin_username: <a href="https://www.linkedin.com/in/eshan-inamdar-465299144/">View my LinkedIn Profile</a> 
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Analytics 10
  <br><br>
  <br><br>
  
  <a href="https://www.linkedin.com/in/eshan-inamdar-465299144/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
