title: Eshan Inamdar # your name (or website title) here
logo: "/images/me.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Consultant
  <br><br>

  I am a highly motivated and results-oriented mechanical engineer having Masters from IIT,Madras with a passion for data analytics. I have 1+ years of experience in data analytics, where I have used my problem-solving and analytical skills to collect, clean, and analyze data to drive business insights. I am proficient in Excel, Python and SQL and I have a proven ability to communicate and present findings effectively.I am keen to enhance my abilities through innovative and challenging projects.

  <br><br>
  
  <a href="https://www.linkedin.com/in/eshan-inamdar-465299144/">View my LinkedIn Profile</a> 
 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
